### PR TITLE
Get (py)ROOT CI to work

### PR DESCRIPTION
**Pull request by olantwin**

### CODE REVIEW

**Comment by chenel** [comment]
Glad this is coming together!  Before we merge this could you just add a quick doc that explains how to use it?  Now is probably the best time, while it's still fresh...

**Comment by olantwin** [comment]
Good idea! I would prefer to do that after the merge though, to make sure everything is working as it is supposed to.

For some reason the matplotlib CI job has disappeared again, and I think that might be because the workflow currently only exists in this PR.

**Comment by chenel** [comment]
Ah, ok.  Just so long as it doesn't get forgotten!

**Review by chenel — APPROVED** [review]

**Comment by olantwin** [comment]
And as I hoped, the matplotlib CI has reappeared.

I'll now get to the commenting and documentation, tracked in #30.

**Pull request merged**
